[build]
  base = "model-converter"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api"
  to = "http://13.221.48.195:8080"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://13.221.48.195:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
