[phases.setup]
nixPkgs = ['python37', 'python37Packages.pip', 'python37Packages.virtualenv']

[phases.install]
cmds = [
  'cp FloorPlanTo3D-API-master/requirements.txt .',
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'cd FloorPlanTo3D-API-master && /opt/venv/bin/python application.py'
