[phases.setup]
nixPkgs = ['python38', 'python38Packages.pip', 'python38Packages.virtualenv']

[phases.install]
cmds = [
  'cp -r FloorPlanTo3D-API-master/* .',
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip==20.3.4',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = '/opt/venv/bin/python application.py'
