[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['cd FloorPlanTo3D-API-master && pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'cd FloorPlanTo3D-API-master && python application.py'
