[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['cd FloorPlanTo3D-API-master && python3 -m pip install --upgrade pip && python3 -m pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'cd FloorPlanTo3D-API-master && python3 application.py'
