[phases.setup]
nixPkgs = ['python38', 'python38Packages.pip', 'stdenv.cc.cc.lib']

[phases.install]
cmds = [
  'cp -r FloorPlanTo3D-API-master/* .',
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip==20.3.4',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'export LD_LIBRARY_PATH=$(find /nix/store -name libstdc++.so.6 -exec dirname {} \; | head -n 1):$LD_LIBRARY_PATH && /opt/venv/bin/python application.py'
