[phases.setup]
nixPkgs = ['python39', 'python39Packages.pip']

[phases.install]
cmds = [
  'cp FloorPlanTo3D-API-master/requirements.txt .',
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = []

[start]
cmd = 'cd FloorPlanTo3D-API-master && python3 application.py'
